### PR TITLE
Remove license in README

### PR DESCRIPTION
**Pull request by mattludwigs**

### CODE REVIEW

**Review by fhunleth — COMMENTED** [review]
It's fine to keep this. The message is accurate and we probably should have a similar block in the other vintage net projects, but different copyright.

**Comment by mattludwigs** [comment]
@frank okay, I thought since we have a `LICENSE` file this wasn't needed?

**Comment by fhunleth** [comment]
Yeah, I've been going back and forth on projects. I'm currently leaning towards having a short blurb at the bottom of the README so that it's a little more obvious. Plus our company has been really supportive of OSSing this stuff, so I like that people see that.

**Comment by mattludwigs** [comment]
@fhunleth I am okay with closing this then :+1:

**Pull request closed without merging**
